/// Para agrupar las tiendas (en caso que se hagan compras en más de una tienda para una cadena)
table cadenas
	lineageTag: b6b575b2-b300-45c7-aa6e-aa6914ee1a9b

	column id
		dataType: int64
		formatString: 0
		lineageTag: 974990e0-6457-4074-9a5f-0085e4ca1d84
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column nombre
		dataType: string
		lineageTag: 30985955-f29e-4f39-844c-fbc1973954f4
		summarizeBy: none
		sourceColumn: nombre

		annotation SummarizationSetBy = Automatic

	partition cadenas = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "Pruebas"),
				    public_cadenas = Source{[Schema="public",Item="cadenas"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(public_cadenas,{"public.tiendas"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

