/// tiendas física donde se realiza la compra
table tiendas
	lineageTag: f7dffff6-3884-48a9-9493-55db72abe2e6

	column id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 85459b06-703b-4447-ad65-9671a306bcfd
		summarizeBy: none
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Tienda
		dataType: string
		lineageTag: 485d813d-614f-4121-9d16-31c93ab87696
		summarizeBy: none
		sourceColumn: Tienda

		annotation SummarizationSetBy = Automatic

	column Direccion
		dataType: string
		lineageTag: d7011ec2-ccb3-41d7-b753-5e85fcde64ab
		summarizeBy: none
		sourceColumn: Direccion

		annotation SummarizationSetBy = Automatic

	/// Asegurar que todas las tiendas tengan al menos una cadena
	column Cadena
		dataType: string
		lineageTag: 0237fe63-7dfa-409c-beee-8fe6aee4e2b3
		summarizeBy: none
		sourceColumn: Cadena

		annotation SummarizationSetBy = Automatic

	partition tiendas = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "Pruebas"),
				    public_tiendas = Source{[Schema="public",Item="tiendas"]}[Data],
				    #"Merged Queries" = Table.NestedJoin(public_tiendas, {"cadena_id"}, cadenas, {"id"}, "cadenas", JoinKind.LeftOuter),
				    #"Expanded cadenas" = Table.ExpandTableColumn(#"Merged Queries", "cadenas", {"nombre"}, {"nombre.1"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded cadenas",{{"nombre.1", "Cadena"}, {"nombre", "Tienda"}, {"direccion", "Direccion"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"public.compras", "public.cadenas", "cadena_id"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

