/// tiendas física donde se realiza la compra
table tiendas
	lineageTag: f7dffff6-3884-48a9-9493-55db72abe2e6

	column id
		dataType: int64
		formatString: 0
		lineageTag: 85459b06-703b-4447-ad65-9671a306bcfd
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = User

	column cadena_id
		dataType: int64
		formatString: 0
		lineageTag: eb6cc64d-d99a-4418-b1f4-e7b1279b9e82
		summarizeBy: none
		sourceColumn: cadena_id

		annotation SummarizationSetBy = Automatic

	column nombre
		dataType: string
		lineageTag: 485d813d-614f-4121-9d16-31c93ab87696
		summarizeBy: none
		sourceColumn: nombre

		annotation SummarizationSetBy = Automatic

	column direccion
		dataType: string
		lineageTag: d7011ec2-ccb3-41d7-b753-5e85fcde64ab
		summarizeBy: none
		sourceColumn: direccion

		annotation SummarizationSetBy = Automatic

	partition tiendas = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "Pruebas"),
				    public_tiendas = Source{[Schema="public",Item="tiendas"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(public_tiendas,{"public.compras", "public.cadenas"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

